/*
 * This file is generated by jOOQ.
 */
package com.pccofvns.ts.domain.tables.records;


import com.pccofvns.ts.domain.tables.RolePermissionX;

import jakarta.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionXRecord extends TableRecordImpl<RolePermissionXRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ts_qa.role_permission_x.role_id</code>.
     */
    public RolePermissionXRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ts_qa.role_permission_x.role_id</code>.
     */
    @NotNull
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ts_qa.role_permission_x.permission_id</code>.
     */
    public RolePermissionXRecord setPermissionId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ts_qa.role_permission_x.permission_id</code>.
     */
    @NotNull
    public Long getPermissionId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RolePermissionX.ROLE_PERMISSION_X.ROLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return RolePermissionX.ROLE_PERMISSION_X.PERMISSION_ID;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public Long component2() {
        return getPermissionId();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public Long value2() {
        return getPermissionId();
    }

    @Override
    public RolePermissionXRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolePermissionXRecord value2(Long value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public RolePermissionXRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionXRecord
     */
    public RolePermissionXRecord() {
        super(RolePermissionX.ROLE_PERMISSION_X);
    }

    /**
     * Create a detached, initialised RolePermissionXRecord
     */
    public RolePermissionXRecord(Long roleId, Long permissionId) {
        super(RolePermissionX.ROLE_PERMISSION_X);

        setRoleId(roleId);
        setPermissionId(permissionId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RolePermissionXRecord
     */
    public RolePermissionXRecord(com.pccofvns.ts.domain.tables.pojos.RolePermissionX value) {
        super(RolePermissionX.ROLE_PERMISSION_X);

        if (value != null) {
            setRoleId(value.roleId());
            setPermissionId(value.permissionId());
            resetChangedOnNotNull();
        }
    }
}
