/*
 * This file is generated by jOOQ.
 */
package com.pccofvns.ts.domain.tables;


import com.pccofvns.ts.domain.Keys;
import com.pccofvns.ts.domain.TsQa;
import com.pccofvns.ts.domain.tables.records.UserRoleXRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleX extends TableImpl<UserRoleXRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ts_qa.user_role_x</code>
     */
    public static final UserRoleX USER_ROLE_X = new UserRoleX();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRoleXRecord> getRecordType() {
        return UserRoleXRecord.class;
    }

    /**
     * The column <code>ts_qa.user_role_x.user_id</code>.
     */
    public final TableField<UserRoleXRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>ts_qa.user_role_x.role_id</code>.
     */
    public final TableField<UserRoleXRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private UserRoleX(Name alias, Table<UserRoleXRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserRoleX(Name alias, Table<UserRoleXRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ts_qa.user_role_x</code> table reference
     */
    public UserRoleX(String alias) {
        this(DSL.name(alias), USER_ROLE_X);
    }

    /**
     * Create an aliased <code>ts_qa.user_role_x</code> table reference
     */
    public UserRoleX(Name alias) {
        this(alias, USER_ROLE_X);
    }

    /**
     * Create a <code>ts_qa.user_role_x</code> table reference
     */
    public UserRoleX() {
        this(DSL.name("user_role_x"), null);
    }

    public <O extends Record> UserRoleX(Table<O> child, ForeignKey<O, UserRoleXRecord> key) {
        super(child, key, USER_ROLE_X);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TsQa.TS_QA;
    }

    @Override
    public List<ForeignKey<UserRoleXRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_ROLE_X_USER_ID, Keys.FK_USER_ROLE_X_ROLE_ID);
    }

    private transient User _user;
    private transient Role _role;

    /**
     * Get the implicit join path to the <code>ts_qa.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.FK_USER_ROLE_X_USER_ID);

        return _user;
    }

    /**
     * Get the implicit join path to the <code>ts_qa.role</code> table.
     */
    public Role role() {
        if (_role == null)
            _role = new Role(this, Keys.FK_USER_ROLE_X_ROLE_ID);

        return _role;
    }

    @Override
    public UserRoleX as(String alias) {
        return new UserRoleX(DSL.name(alias), this);
    }

    @Override
    public UserRoleX as(Name alias) {
        return new UserRoleX(alias, this);
    }

    @Override
    public UserRoleX as(Table<?> alias) {
        return new UserRoleX(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRoleX rename(String name) {
        return new UserRoleX(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRoleX rename(Name name) {
        return new UserRoleX(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRoleX rename(Table<?> name) {
        return new UserRoleX(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
