/*
 * This file is generated by jOOQ.
 */
package com.pccofvns.ts.domain;


import com.pccofvns.ts.domain.tables.Permission;
import com.pccofvns.ts.domain.tables.Role;
import com.pccofvns.ts.domain.tables.RolePermissionX;
import com.pccofvns.ts.domain.tables.User;
import com.pccofvns.ts.domain.tables.UserRoleX;


/**
 * Convenience access to all tables in ts_qa.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ts_qa.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>ts_qa.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>ts_qa.role_permission_x</code>.
     */
    public static final RolePermissionX ROLE_PERMISSION_X = RolePermissionX.ROLE_PERMISSION_X;

    /**
     * The table <code>ts_qa.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>ts_qa.user_role_x</code>.
     */
    public static final UserRoleX USER_ROLE_X = UserRoleX.USER_ROLE_X;
}
