/*
 * This file is generated by jOOQ.
 */
package com.pccofvns.ts.domain;


import com.pccofvns.ts.domain.tables.Permission;
import com.pccofvns.ts.domain.tables.Role;
import com.pccofvns.ts.domain.tables.RolePermissionX;
import com.pccofvns.ts.domain.tables.User;
import com.pccofvns.ts.domain.tables.UserRoleX;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ts extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ts</code>
     */
    public static final Ts TS = new Ts();

    /**
     * The table <code>ts.permission</code>.
     */
    public final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>ts.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>ts.role_permission_x</code>.
     */
    public final RolePermissionX ROLE_PERMISSION_X = RolePermissionX.ROLE_PERMISSION_X;

    /**
     * The table <code>ts.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>ts.user_role_x</code>.
     */
    public final UserRoleX USER_ROLE_X = UserRoleX.USER_ROLE_X;

    /**
     * No further instances allowed
     */
    private Ts() {
        super("ts", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Permission.PERMISSION,
            Role.ROLE,
            RolePermissionX.ROLE_PERMISSION_X,
            User.USER,
            UserRoleX.USER_ROLE_X
        );
    }
}
